let prodJson = [
    {id:1, name:'Massagem Express Localizada -<br> (Costas, Pés, Pernas, Cabeça<br> 1 região à escolha)', img:'img/massagem/1.jpg', price:99.00, sizes:['25',], description:'De acordo com sua necessidade para ter um relaxamento e alívio instantâneo na região onde sente mais tensão. <br><br>(essa massagem só dura 25 minutos)'},
    {id:2, name:'Massagem Profunda – Deep Tissue Massage', img:'img/massagem/3.png',price:249.00, sizes:['80', '50', '110'], description:'Massagem profunda tem como objetivo; aliviar o stress, dores musculares e promover  a boa saúde e bem-estar. Existem várias técnicas de massagens terapêuticas que podem ajudar no equilíbrio da saúde física, emocional e mental, entre elas está também a Deep Tissue Massage (massagem profunda) que pode trazer outros benefícios. <br><br>(50 min R$ 249.00, 80 min R$ 329.00,<br> 110 min R$ 409.00)'},
    {id:3, name:'Massagem a 4 Mãos ', img:'img/massagem/4.png', price:349.00, sizes:['80', '50', '110'], description:'A massagem a quatro mãos é realizada por dois massoterapeutas simultaneamente, aplicada nos lados direito e esquerdo do corpo, proporcionando ao paciente duplo relaxamento <br><br>  (50 minutos)'},
    {id:4, name:'Massagem Abhyanga', img:'img/massagem/5.png', price:249.00, sizes:['80', '50', '110'], description:'É uma massagem relaxante e que promove a drenagem, mas seu objetivo é terapêutico. Ela trabalha o corpo nos quatro níveis: psíquico, energético, fisiológico e estrutural. <br><br> (50 min R$ 249.00, 80 min R$ 329.00,<br> 110 min R$ 409.00)'},
    {id:5, name:'Massagem C/ Pedras Quentes', img:'img/massagem/4(1).png', price:249.00, sizes:['80', '50', '110'], description:' Em um aquecedor próprio, as pedras chegam a 42 ºC, sendo a temperatura ideal para serem colocadas por todo o corpo. Após serem distribuídas pelos músculos vitais, manobras específicas são feitas com a utilização de óleos específicos para facilitar no deslize das pedras, proporcionando uma sensação de bem-estar e relaxamento. <br><br> (50 min R$ 249.00, 80 min R$ 329.00,<br> 110 min R$ 409.00)'},
    {id:6, name:'Massagem Para Gestantes', img:'img/massagem/6.png', price:249.99, sizes:['80', '50', '110'], description:'Esta massagem com movimentos suaves e drenantes, estimula a circulação e alivia todos os estados de tensão próprios da mulher grávida. Transmite sensações puras de relaxamento, harmonia e bem-estar, momentos únicos de ligação ao seu bebé. <br><br> (50 min R$ 249.00, 80 min R$ 329.00,<br> 110 min R$ 409.00)'},
    {id:7, name:'Reflexologia Tailandesa', img:'img/massagem/7.png', price:198.00, sizes:[ '50'], description:'A Reflexologia Tailandesa (Thai Foot Reflexology), além de uma massagem, é também um tratamento energético que restaura o fluxo de energia vital do corpo através das Linhas Sem (Meridianos de energia) que estão ligadas aos pontos reflexos dos pés e pernas.  Restaura o equilíbrio da mente e do corpo e ao mesmo tempo estimula os órgãos internos além de ser um tratamento de relaxamento maravilhoso para os membros inferiores. <br>Combina uma variedade de técnicas manuais como: alongamento, torção, amassamento, pressões de polegar e em conjunto com um bastão de madeira sagrada, Stick, o que a torna única e diferenciada.<br><br> (50 min R$ 149.00)'},
    {id:7, name:'Massagem Ayurvédica Terapêutica (no tatame)', img:'img/massagem/8.jpg', price:249.00, sizes:['80', '50', '110'], description:'Baseada na Medicina Ayurveda, a Massagem Ayurvédica utiliza alongamentos e movimentos ascendentes para energizar os chacras. <br>Esta massagem é realizada na maca ou no tatame e utiliza óleo vegetal 100% puro. <br>Algumas manobras são realizadas com os pés, fazendo desta massagem uma experiência única. <br><br> (50 min R$ 249.00, 80 min R$ 329.00,<br> 110 min R$ 409.00)'}
  ];